-- MySQL Script generated by MySQL Workbench
-- Wed May  7 14:50:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema photo_center
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema photo_center
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `photo_center` DEFAULT CHARACTER SET utf8 ;
USE `photo_center` ;

-- -----------------------------------------------------
-- Table `photo_center`.`branches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photo_center`.`branches` (
  `id_branch` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NOT NULL,
  `number_employees` INT NOT NULL,
  `kiosk_address` VARCHAR(45) NOT NULL,
  `kiosk_number_employees` INT NOT NULL,
  PRIMARY KEY (`id_branch`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photo_center`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photo_center`.`clients` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `client_name` VARCHAR(45) NOT NULL,
  `client_surname` VARCHAR(45) NOT NULL,
  `gender` ENUM("Мужской", "Женский", "Не указан") NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `discount` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photo_center`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photo_center`.`employees` (
  `id_employee` INT NOT NULL AUTO_INCREMENT,
  `id_branch` INT NOT NULL,
  `employee_name` VARCHAR(45) NOT NULL,
  `employee_surname` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_employee`),
  INDEX `id_branch_idx` (`id_branch` ASC) VISIBLE,
  CONSTRAINT `id_branch`
    FOREIGN KEY (`id_branch`)
    REFERENCES `photo_center`.`branches` (`id_branch`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photo_center`.`units`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photo_center`.`units` (
  `id_unit` INT NOT NULL AUTO_INCREMENT,
  `unit` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_unit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photo_center`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photo_center`.`products` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `id_unit` INT NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `product_type` ENUM("Услуга", "Доп. услуга", "Товар") NOT NULL,
  `price` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`id_product`),
  INDEX `id_unit_idx` (`id_unit` ASC) VISIBLE,
  CONSTRAINT `id_unit`
    FOREIGN KEY (`id_unit`)
    REFERENCES `photo_center`.`units` (`id_unit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photo_center`.`format_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photo_center`.`format_types` (
  `id_format_type` INT NOT NULL AUTO_INCREMENT,
  `format_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_format_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photo_center`.`paper_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photo_center`.`paper_types` (
  `id_paper_type` INT NOT NULL AUTO_INCREMENT,
  `paper_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_paper_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photo_center`.`payment_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photo_center`.`payment_types` (
  `id_payment_type` INT NOT NULL AUTO_INCREMENT,
  `payment_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_payment_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photo_center`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photo_center`.`orders` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `id_branch` INT NOT NULL,
  `id_employee` INT NOT NULL,
  `id_client` INT NOT NULL,
  `id_product` INT NOT NULL,
  `id_format_type` INT NOT NULL,
  `id_paper_type` INT NOT NULL,
  `id_payment_type` INT NOT NULL,
  `order_status` ENUM("Оплачен", "Выполняется", "Завершен") NOT NULL,
  `order_place` ENUM("Филиал", "Киоск") NOT NULL,
  `order_type` ENUM("Срочный", "Несрочный") NOT NULL,
  `order_date` DATETIME NOT NULL,
  `completion_date` DATETIME NOT NULL,
  `number_photos` INT NOT NULL,
  `discount` DECIMAL(3,2) NOT NULL,
  `price` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`id_order`),
  INDEX `id_branch_idx` (`id_branch` ASC) VISIBLE,
  INDEX `id_client_idx` (`id_client` ASC) VISIBLE,
  INDEX `fk_orders_products1_idx` (`id_product` ASC) VISIBLE,
  INDEX `fk_orders_information1_idx` (`id_format_type` ASC) VISIBLE,
  INDEX `id_paper_type_idx` (`id_paper_type` ASC) VISIBLE,
  INDEX `id_payment_type_idx` (`id_payment_type` ASC) VISIBLE,
  INDEX `id_employee_idx` (`id_employee` ASC) VISIBLE,
  CONSTRAINT `id_branch_order`
    FOREIGN KEY (`id_branch`)
    REFERENCES `photo_center`.`branches` (`id_branch`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_client_order`
    FOREIGN KEY (`id_client`)
    REFERENCES `photo_center`.`clients` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_product`
    FOREIGN KEY (`id_product`)
    REFERENCES `photo_center`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_format`
    FOREIGN KEY (`id_format_type`)
    REFERENCES `photo_center`.`format_types` (`id_format_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_paper_type`
    FOREIGN KEY (`id_paper_type`)
    REFERENCES `photo_center`.`paper_types` (`id_paper_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_payment_type_order`
    FOREIGN KEY (`id_payment_type`)
    REFERENCES `photo_center`.`payment_types` (`id_payment_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_employee_order`
    FOREIGN KEY (`id_employee`)
    REFERENCES `photo_center`.`employees` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photo_center`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photo_center`.`sales` (
  `id_sale` INT NOT NULL AUTO_INCREMENT,
  `id_branch` INT NOT NULL,
  `id_employee` INT NOT NULL,
  `id_client` INT NOT NULL,
  `id_payment_type` INT NOT NULL,
  `sale_status` ENUM("Оплачен", "Выполняется", "Завершен") NOT NULL,
  `order_date` DATETIME NOT NULL,
  `completion_date` DATETIME NOT NULL,
  `price` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`id_sale`),
  INDEX `id_client_idx` (`id_client` ASC) VISIBLE,
  INDEX `id_employee_idx` (`id_employee` ASC) VISIBLE,
  INDEX `id_kiosk_idx` (`id_branch` ASC) VISIBLE,
  INDEX `id_payment_type_idx` (`id_payment_type` ASC) VISIBLE,
  CONSTRAINT `id_client`
    FOREIGN KEY (`id_client`)
    REFERENCES `photo_center`.`clients` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_employee`
    FOREIGN KEY (`id_employee`)
    REFERENCES `photo_center`.`employees` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_kiosk`
    FOREIGN KEY (`id_branch`)
    REFERENCES `photo_center`.`branches` (`id_branch`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_payment_type`
    FOREIGN KEY (`id_payment_type`)
    REFERENCES `photo_center`.`payment_types` (`id_payment_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photo_center`.`products_in_sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photo_center`.`products_in_sales` (
  `id_sale` INT NOT NULL,
  `id_product` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id_sale`, `id_product`),
  INDEX `fk_products_has_sales_sales1_idx` (`id_sale` ASC) VISIBLE,
  INDEX `fk_products_has_sales_products1_idx` (`id_product` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_sales_products1`
    FOREIGN KEY (`id_product`)
    REFERENCES `photo_center`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_sales_sales1`
    FOREIGN KEY (`id_sale`)
    REFERENCES `photo_center`.`sales` (`id_sale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
